<?xml version="1.0"?>
<package format="3">
  <name>botarm_hardware</name>
  <version>0.1.0</version>
  <description>ros2_control hardware plugin for the Botarm robot</description>

  <maintainer email="emmanuel@email.com">emmanuel</maintainer>
  <license>BSD-3-Clause</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>hardware_interface</depend>
  <depend>pluginlib</depend>
  <depend>rclcpp</depend>
  <depend>rclcpp_lifecycle</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
